[messenger]
# 使用了Server酱的推送服务
# 如果想开启下单成功后消息推送，则将 enable 设置为 true，默认为 false 不开启推送
# 开启消息推送必须填入 sckey，如何获取请参考 http://sc.ftqq.com/3.version。感谢Server酱～
enable = True
sckey = ''

[info]
userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
# 以下为预约者的信息
stuid = ''
pwd = ''
name = ''
# 以下为预约访客的信息
GuestName = '
GuestTel = ''
GuestIdcard = ''
GuestSex = ''
GuestTime = ''